services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - ${ADMINER_PORT}:8080

volumes:
  db-data:
