services:
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./data/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - '5432:5432'
  
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - '8080:8080'
    depends_on:
      - postgres

volumes:
  db-data: