services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - ${ADMINER_PORT}:8080

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:8080

volumes:
  db-data:
  nominatim-data:
