openapi: 3.0.0
info:
  title: A'rosa-je API
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
paths:
  /users:
    post:
      summary: Créer un nouvel utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Utilisateur créé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /auth/login:
    post:
      summary: Authentification de l'utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Utilisateur authentifié avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string

  /plants:
    get:
      summary: Récupérer la liste des plantes
      responses:
        '200':
          description: Liste des plantes récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Plant'
    post:
      summary: Ajouter une nouvelle plante
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Plant'
      responses:
        '201':
          description: Plante ajoutée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plant'

  /plants/{plantId}:
    get:
      summary: Récupérer une plante par son ID
      parameters:
        - name: plantId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Plante récupérée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plant'
    put:
      summary: Mettre à jour une plante par son ID
      parameters:
        - name: plantId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Plant'
      responses:
        '200':
          description: Plante mise à jour avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plant'
    delete:
      summary: Supprimer une plante par son ID
      parameters:
        - name: plantId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Plante supprimée avec succès

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
          format: email
        password:
          type: string
        firstName:
          type: string
        lastName:
          type: string

    Location:
      type: object
      properties:
        address:
          type: string
        zip:
          type: string
        city:
          type: string
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double

    Plant:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        species:
          type: string
        location:
          $ref: '#/components/schemas/Location'
